### PR TITLE
WIP: improve: get cpu number in container

### LINKED ISSUE #313: k8s 集群内部署的话直接用NumCPU()获取不到真实可用核心数
https://github.com/apache/dubbo-go-pixiu/blob/develop/cmd/pixiu/pixiu.go#L151

这里是不是有点问题. 在 k8s 集群内部署的话直接用NumCPU()获取不到真实可用核心数. 会导致调度不合理延迟加大.

from others

### PR DESCRIPTION
**Pull request by marlonfan**
**What this PR does**:

Optimize the method of getting the number of cpu in the container

**Which issue(s) this PR fixes**:

Fixes #313 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

 NONE

### CODE REVIEW

**Comment by marlonfan** [comment]
The upstream zookeeper library has had a break change, should I consider replacing it with the zookeeper client from the gost repository? pls help.

**Comment by marlonfan** [comment]
## Some related modifications:

- [dubbogo/gost](https://github.com/dubbogo/gost/pull/79)
- [dubbogo/go-zookeeper](https://github.com/dubbogo/go-zookeeper/pull/9)

**Comment by ztelur** [comment]
Thanks for PR again. It seems that dubbogo uses go-zookeeper v1.0.4-0.20211212162352. I am also a little confused with two zk library. @justxuewei @AlexStocks

**Review by AlexStocks — APPROVED** [review]

**Comment by mark4z** [comment]
fix ci pls

**Review by xiaoliu10 — APPROVED** [review]

**Pull request closed without merging**
