### PR TITLE
dynamic Router and Cluster from registry center

### PR DESCRIPTION
**Pull request by FoghostCn**
**What this PR does**:

dynamic Router and Cluster from registry center

ref #600

**Special notes for your reviewer**:

support application level and interface level service discovery
support zk and nacos registry

application level service discovery use prefix url pattern to match http path,beacuse there is  no methods information in the registry.

**Does this PR introduce a user-facing change?**:

```yaml
  adapters:
    - id: test
      name: dgp.adapter.dubboregistrycenter
      config:
        registries:
          "zookeeper":
            registry_type: application // new config field, support "application" or "interface" 
            protocol: zookeeper
            address: "127.0.0.1:2181"
            timeout: "5s"

```

### demo project 

https://github.com/FoghostCn/dubbo-go-pixiu-samples/blob/feature-registry-center/dubbogo/simple/zookeeper

* dubbo server: server/app/server.go
* test case: test/pixiu_test.go
* pixiu config: pixiu/conf.yaml

```yaml
static_resources:
  listeners:
    - name: "net/http"
      protocol_type: "HTTP"
      address:
        socket_address:
          address: "0.0.0.0"
          port: 8881
      filter_chains:
        filters:
          - name: dgp.filter.httpconnectionmanager
            config:
              route_config:
                dynamic: true
              http_filters:
                - name: dgp.filter.http.directdubboproxy
                  config:
  adapters:
    - id: test
      name: dgp.adapter.dubboregistrycenter
      config:
        registries:
          "zookeeper":
            registry_type: application # or interface
            protocol: zookeeper
            address: "127.0.0.1:2181"
            timeout: "5s"
```

### CODE REVIEW

**Comment by mark4z** [comment]
升级3.1.1的时候屏蔽掉了几个UT，现在应该可以打开了

**Comment by AlexStocks** [comment]
ci 失败，check 下看看

**Comment by AlexStocks** [comment]
@coderabbitai review

**Comment by AlexStocks** [comment]
[@CodiumAI-Agent](https://github.com/CodiumAI-Agent) /review

**Comment by FoghostCn** [comment]
ci失败是预期内，因为 https://github.com/apache/dubbo-go-pixiu/issues/600#issuecomment-2016656779

**Comment by FoghostCn** [comment]
ci fixed in https://github.com/apache/dubbo-go-pixiu-samples/pull/58

**Comment by FoghostCn** [comment]
ignore envoy ci failed -> CI / Go Test ubuntu-latest - Go 1.18 (pull_request_target) Failing after 41s

**Comment by mark4z** [comment]
Good job

**Pull request merged**
