### PR TITLE
Feature:Add Graceful Shutdown

### PR DESCRIPTION
**Pull request by A-Wanderer**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mark4z** [comment]
remove test to samples

**Comment by A-Wanderer** [comment]
samples:   https://github.com/dubbo-go-pixiu/samples/pull/22

**Review by MasterKenway — APPROVED** [review]

**Comment by mark4z** [comment]
go fmt

**Comment by PhilYue** [comment]
> samples: [dubbo-go-pixiu/samples#22](https://github.com/dubbo-go-pixiu/samples/pull/22)

The new PR https://github.com/apache/dubbo-go-pixiu-samples/pull/1

**Review by mark4z — APPROVED** [review]
LGTM

**Review by PhilYue — APPROVED** [review]

**Pull request merged**
